djangopanel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls'))
]

panel/urls.py
from django.urls import path
from panel import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('budynki/<int:id>/', views.budynki_view, name='budynki_view'),
    path('formularz-zgloszeniowy/', views.formularz_zgloszeniowy, name='formularz_zgloszeniowy'),
    path('pobierz-budynki/', views.pobierz_budynki, name='pobierz_budynki'),
    path('potwierdzenie/', views.ConfirmForm.as_view(), name='potwierdzenie'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords
import re
from django.core.exceptions import ValidationError
import qrcode
from io import BytesIO
from django.core.files.base import ContentFile
from django.contrib.auth.models import User


class Spoldzielnia(models.Model):
	nazwa = models.CharField(max_length=100, unique=True)
	miasto = models.CharField(max_length=100)
	ulica = models.CharField(max_length=100)
	kod = models.CharField(max_length=10)
	rok_zalozenia = models.PositiveIntegerField()
	email = models.EmailField(null=True, blank=True)
	strona_www = models.URLField(max_length=200, null=True, blank=True)
	facebook = models.URLField(max_length=200, null=True, blank=True)
	instagram = models.URLField(max_length=200, null=True, blank=True)
	linkedin = models.URLField(max_length=200, null=True, blank=True)
	history = HistoricalRecords()
	
	def clean(self):
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.nazwa):
			raise ValidationError({'nazwa': "Pole 'Nazwa' może zawierać tylko litery z polskiego alfabetu."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.miasto):
			raise ValidationError({'miasto': "Pole 'Miasto' może zawierać tylko litery z polskiego alfabetu."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż0-9\s]+$', self.ulica):
			raise ValidationError(
				{'ulica': "Pole 'Ulica' może zawierać tylko litery polskiego alfabetu, cyfry oraz spacje."})
		
		if not re.match(r'^\d{2}-\d{3}$', self.kod):
			raise ValidationError({'kod': "Pole 'Kod' musi być w formacie xx-xxx, gdzie x to cyfry."})
	
	def save(self, *args, **kwargs):
		if re.match(r'^\d{6}$', self.kod):
			self.kod = f'{self.kod[:3]}-{self.kod[2:]}'
		super().save(*args, **kwargs)
	
	def __str__(self):
		return f'{self.nazwa} | {self.miasto}'
	
	class Meta:
		verbose_name = _('Spółdzielnia')
		verbose_name_plural = _('Spółdzielnia')


class AdministracjaOsiedla(models.Model):
	nazwa = models.CharField(max_length=100, null=True, blank=True)
	ulica = models.CharField(max_length=100, null=True, blank=True)
	telefon = models.CharField(max_length=15, null=True, blank=True)
	email_administracja = models.EmailField(null=True, blank=True)
	spoldzielnia = models.ForeignKey('Spoldzielnia', on_delete=models.CASCADE, related_name='administracje')
	history = HistoricalRecords()
	
	def clean(self):
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.nazwa):
			raise ValidationError({'nazwa': "Pole 'Nazwa' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż0-9\s]+$', self.ulica):
			raise ValidationError(
				{'ulica': "Pole 'Ulica' może zawierać tylko litery polskiego alfabetu, cyfry oraz spacje."})
		
		if not re.match(r'^\d+$', self.telefon):
			raise ValidationError({'telefon': "Pole 'Telefon' może zawierać tylko cyfry."})
	
	def __str__(self):
		return f'{self.nazwa}'
	
	class Meta:
		verbose_name = _('Administracja Osiedla')
		verbose_name_plural = _('Administracje Osiedli')


class Kierownik(models.Model):
	imie_kierownik = models.CharField(max_length=100, null=True, blank=True)
	nazwisko_kierownik = models.CharField(max_length=100, null=True, blank=True)
	imie_zastepca = models.CharField(max_length=100, null=True, blank=True)
	nazwisko_zastepca = models.CharField(max_length=100, null=True, blank=True)
	email_kierownik = models.EmailField(null=True, blank=True)
	telefon_kierownik = models.CharField(max_length=15, null=True, blank=True)
	osiedle = models.ForeignKey('AdministracjaOsiedla', on_delete=models.CASCADE, related_name='kierownicy')
	foto_kierownik = models.ImageField(blank=True, null=True, upload_to='fotos/')
	history = HistoricalRecords()
	
	def clean(self):
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.imie_kierownik):
			raise ValidationError(
				{'imie_kierownik': "Pole 'Imię' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.nazwisko_kierownik):
			raise ValidationError(
				{'nazwisko_kierownik': "Pole 'Nazwisko' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.imie_zastepca):
			raise ValidationError(
				{'imie_zastepca': "Pole 'Imię' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.nazwisko_zastepca):
			raise ValidationError(
				{'nazwisko_zastepca': "Pole 'Nazwisko' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^\d+$', self.telefon_kierownik):
			raise ValidationError({'telefon_kierownik': "Pole 'Telefon komórkowy' może zawierać tylko cyfry."})
	
	def __str__(self):
		return f'{self.imie_kierownik} {self.nazwisko_kierownik} | {self.osiedle}'
	
	class Meta:
		verbose_name = _('Kierownik')
		verbose_name_plural = _('Kierownik')


class Administrator(models.Model):
	imie_administrator = models.CharField(max_length=100, null=True, blank=True)
	nazwisko_administrator = models.CharField(max_length=100, null=True, blank=True)
	email_administrator = models.EmailField(null=True, blank=True)
	komorka_administrator = models.CharField(max_length=15, null=True, blank=True)
	telefon_stacjonarny_administrator = models.CharField(max_length=15, null=True, blank=True)
	foto_administrator = models.ImageField(blank=True, null=True, upload_to='fotos/')
	osiedle = models.ForeignKey('AdministracjaOsiedla', on_delete=models.CASCADE, related_name='administratorzy')
	history = HistoricalRecords()
	
	def clean(self):
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.imie_administrator):
			raise ValidationError(
				{'imie_administrator': "Pole 'Imię' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż\s]+$', self.nazwisko_administrator):
			raise ValidationError(
				{'nazwisko_administrator': "Pole 'Nazwisko' może zawierać tylko litery polskiego alfabetu i spacje."})
		
		if not re.match(r'^\d+$', self.komorka_administrator):
			raise ValidationError({'komorka_administrator': "Pole 'Telefon komórkowy' może zawierać tylko cyfry."})
		
		if not re.match(r'^\d+$', self.telefon_stacjonarny_administrator):
			raise ValidationError(
				{'telefon_stacjonarny_administrator': "Pole 'Telefon stacjonarny' może zawierać tylko cyfry."})
	
	def __str__(self):
		return f'{self.imie_administrator} {self.nazwisko_administrator} | {self.osiedle}'
	
	class Meta:
		verbose_name = _('Administrator')
		verbose_name_plural = _('Administrator')


class Budynek(models.Model):
	indeks = models.CharField(max_length=10, unique=True, null=True, blank=True)
	ulica = models.CharField(max_length=100)
	kod = models.CharField(max_length=10, null=True, blank=True)
	kierownik = models.ForeignKey('Kierownik', on_delete=models.SET_NULL, null=True, blank=True, related_name='budynki')
	osiedle = models.ForeignKey('AdministracjaOsiedla', on_delete=models.CASCADE, null=True, blank=True,
								related_name='budynki')
	spoldzielnia = models.ForeignKey('Spoldzielnia', on_delete=models.CASCADE, null=True, blank=True,
									 related_name='budynki')
	administrator = models.ForeignKey('Administrator', on_delete=models.SET_NULL, null=True, blank=True,
									  related_name='budynki')
	foto = models.ImageField(upload_to='budynki_foto/', null=True, blank=True)
	rok_budowy = models.CharField(max_length=20, null=True, blank=True)
	telefon_osiedla = models.CharField(max_length=20, null=True, blank=True)
	obreb = models.CharField(max_length=100, null=True, blank=True)
	dzialka = models.CharField(max_length=50, null=True, blank=True)
	laczna_powierzchnia_dzialki = models.CharField(max_length=50, null=True, blank=True)
	powierzchnia_wspolna_budynku = models.CharField(max_length=50, null=True, blank=True)
	history = HistoricalRecords()
	
	def __str__(self):
		return f'{self.ulica} | {self.administrator}'
	
	class Meta:
		verbose_name = _('Budynek')
		verbose_name_plural = _('Budynki')


class Finanse(models.Model):
	budynek = models.ForeignKey('Budynek', on_delete=models.CASCADE, related_name='finanse')
	fundusz_remontowy = models.CharField(max_length=50, null=True, blank=True)
	zadluzenie_budynku = models.CharField(max_length=50, null=True, blank=True)
	history = HistoricalRecords()
	
	def clean(self):
		if not re.match(r'^[0-9,;.]*$', self.fundusz_remontowy):
			raise ValidationError(
				{'fundusz_remontowy': "Pole 'Fundusz remontowy' może zawierać tylko cyfry oraz znaki: , ; ."})
		
		if not re.match(r'^[0-9,;.]*$', self.zadluzenie_budynku):
			raise ValidationError(
				{'zadluzenie_budynku': "Pole 'Zadłużenie budynku' może zawierać tylko cyfry oraz znaki: , ; ."})
	
	def __str__(self):
		return f'{self.budynek.ulica}'
	
	class Meta:
		verbose_name = _('Finanse')
		verbose_name_plural = _('Finanse')


class Remonty(models.Model):
	budynek = models.ForeignKey('Budynek', on_delete=models.CASCADE, related_name='remonty')
	wykonawca = models.CharField('Wykonawca', max_length=100, null=True, blank=True)
	opis_remontu = models.TextField(null=True, blank=True)
	poczatek_prac = models.DateField(null=True, blank=True)
	koniec_prac = models.DateField(null=True, blank=True)
	uchwala = models.FileField(upload_to='uchwaly/', null=True, blank=True)
	ankieta = models.FileField(upload_to='ankiety/', null=True, blank=True)
	history = HistoricalRecords()
	
	def __str__(self):
		return f'{self.wykonawca} | {self.budynek.ulica} | {self.koniec_prac}'
	
	class Meta:
		verbose_name = _('Remonty')
		verbose_name_plural = _('Remonty')


class Przeglady(models.Model):
	budynek = models.ForeignKey('Budynek', on_delete=models.CASCADE, related_name='przeglady')
	planowany_przeglad_kominiarski = models.CharField(_('Planowany przegląd kominiarski'), max_length=255, blank=True,
													  null=True)
	planowany_przeglad_gazowy = models.CharField(_('Planowany przegląd gazowy'), max_length=255, blank=True, null=True)

panel/forms.py
from django import forms
from django.conf import settings
from .models import Kierownik, Administrator, AdministracjaOsiedla, Budynek
from django.core.mail import send_mail
from smsapi.client import SmsApiPlClient


class BulkUpdateForm(forms.Form):
    kierownik = forms.ModelChoiceField(queryset=Kierownik.objects.all(), required=False)
    osiedle = forms.ModelChoiceField(queryset=AdministracjaOsiedla.objects.all(), required=False)
    administrator = forms.ModelChoiceField(queryset=Administrator.objects.all(), required=False)


class CsvImportForm(forms.Form):
    csv_file = forms.FileField()
    

class ExcelImportForm(forms.Form):
    excel_file = forms.FileField(label="Wybierz plik Excel")


class FormularzZgloszeniowyForm(forms.Form):
    osiedle = forms.ModelChoiceField(
        queryset=AdministracjaOsiedla.objects.all(),
        label="Wybierz osiedle",
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    budynek = forms.ModelChoiceField(
        queryset=Budynek.objects.none(),
        label="Wybierz budynek",
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    temat = forms.CharField(
        max_length=100,
        label="Temat zgłoszenia",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label="Treść zgłoszenia"
    )
    phone = forms.CharField(
        max_length=15,
        label="Numer telefonu",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'np. +48123456789'})
    )

    def __init__(self, *args, **kwargs):
        osiedle_id = kwargs.pop('osiedle_id', None)
        super().__init__(*args, **kwargs)

        if osiedle_id:
            self.fields['budynek'].queryset = Budynek.objects.filter(osiedle_id=osiedle_id)
        elif 'osiedle' in self.data:
            try:
                osiedle_id = int(self.data.get('osiedle'))
                self.fields['budynek'].queryset = Budynek.objects.filter(osiedle_id=osiedle_id)
            except (ValueError, TypeError):
                self.fields['budynek'].queryset = Budynek.objects.none()
        else:
            self.fields['budynek'].queryset = Budynek.objects.none()

    def send_email(self):
        osiedle = self.cleaned_data['osiedle']
        temat = self.cleaned_data['temat']
        content = self.cleaned_data['content']
        phone = self.cleaned_data['phone']
        email_administracja = osiedle.email_administracja

        message = f"Temat: {temat}\n\nTreść: {content}\n\nNumer telefonu: {phone}"
        send_mail(
            subject=temat,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[email_administracja],
        )

    def send_sms(self):
        phone = self.cleaned_data['phone']
        content = "Twoje zgłoszenie zostało pomyślnie wysłane do administracji. Skontaktujemy się z Tobą wkrótce."

        to_replace = {
            "ą": "a", "Ą": "A", "ś": "s", "Ś": "S", "ę": "e", "Ę": "E",
            "ł": "l", "Ł": "L", "ó": "o", "Ó": "O", "ń": "n", "Ń": "N",
            "ć": "c", "Ć": "C", "ż": "z", "Ż": "Z", "ź": "z", "Ź": "Z",
            '„': "", '”': ""
        }
        for char, replacement in to_replace.items():
            content = content.replace(char, replacement)

        token = "SGfuxxeDr8GYAWMOXp1kzx18ZT5hTuKp60Cw69en"
        client = SmsApiPlClient(access_token=token)
        client.sms.send(to=phone, message=content, from_="SMBUDOWLANI")

panel/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="IT HELP">
    <meta name="description" content="Panel mieszkańca, remonty, przeglady, spółdzielnia, administracja, polska">
    <meta name="keywords"
          content="Panel mieszkańca">
    <meta name="robots" content="all">
    <title>Panel Mieszkańca - wszystko w jednym</title>
{#    <link rel="stylesheet" href="{% static 'assets/images/favicon.png' %}">#}
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/magnific-popup/magnific-popup.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/scrollcue/scrollcue.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/swiper/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/font-awesome/css/all.css' %}">


</head>
<body data-preloader="1">

{% include 'navbar.html' %}

{% block content %}

{% endblock %}


<script src="{% static 'assets/plugins/jquery.min.js' %}"></script>
<script src="{% static 'assets/plugins/plugins.js' %}"></script>
<script src="{% static 'assets/js/functions.js' %}"></script>


</body>
</html>

panel/templates/base_sm.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Panel Mieszkańca</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-icons/bootstrap-icons.css' %}">
</head>
<body>
{% include 'navbar_sm.html' %}

<div class="container">
    <br>
    {% block content %}
    {% endblock %}
</div>

<div class="scrolltotop" style="position: fixed; bottom: 20px; right: 20px; z-index: 1000;">
    <a href="#" style="
        display: flex;
        justify-content: center;
        align-items: center;
        width: 50px;
        height: 50px;
        background-color: #6c757d;
        color: white;
        border-radius: 50%;
        text-decoration: none;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        transition: background-color 0.3s, box-shadow 0.3s;">
        <i class="bi bi-arrow-up" style="font-size: 24px;"></i>
    </a>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    document.querySelector('.scrolltotop a').addEventListener('click', function (e) {
        e.preventDefault();
        window.scrollTo({ top: 0, behavior: 'smooth' }); 
    });

    const scrollButton = document.querySelector('.scrolltotop');
    window.addEventListener('scroll', function () {
        if (window.scrollY > 200) { 
            scrollButton.style.display = 'flex';
        } else {
            scrollButton.style.display = 'none';
        }
    });

    scrollButton.style.display = 'none';
</script>

</body>
</html>

panel/templates/confirm.html
{% extends 'base_sm.html' %}
{% block content %}
    <div class="container my-4">
        <h2 class="text-center">Zgłoszenie</h2>
        <div class="card shadow-sm mx-auto" style="max-width: 600px;">
            <div class="card-body">
                <h6>Dziękujemy za zgłoszenie!</h6>
                <p>Twoje zgłoszenie zostało pomyślnie wysłane do administracji. Skontaktujemy się z Tobą wkrótce.</p>
                <a href="{% url 'dashboard' %}" class="btn btn-primary btn-block">Wróć do strony głównej</a>
            </div>
        </div>
    </div>
{% endblock %}

panel/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Sekcja wyszukiwania -->
    <div class="section py-3">
        <div class="container">
            {% if query %}
                <h5 class="text-center">Wyniki dla frazy: <strong>"{{ query }}"</strong></h5>
            {% endif %}
        </div>
    </div>

    <!-- Początek Sekcji Karty -->
    <div class="section py-5">
        <div class="container">
            <div class="row">
                {% if budynki %}
                    {% for budynek in budynki %}
                        <div class="col-12 col-md-6 col-lg-3 mb-4">
                            <div class="card text-center border-dark h-100"
                                 style="background-color: #e8f6f3; border-color: #9ad1d4;">
                                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                                    <i class="bi bi-building display-4 mb-3" style="color: #6c757d;"></i>
                                    <h5 class="card-title" style="color: #5a6268;">{{ budynek.ulica }}</h5>
                                    <p class="card-text" style="color: #6c757d;">Sprawdź szczegóły budynku.</p>
                                    <a href="{% url 'budynki_view' budynek.id %}"
                                       class="btn btn-outline-dark">Zobacz</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p class="text-muted text-center">Nie znaleziono budynków pasujących do frazy
                        "<strong>{{ query }}</strong>".</p>
                {% endif %}
            </div>

            <!-- Koniec Sekcji Karty -->

            <!-- Początek Sekcji Paginacja -->
            <nav aria-label="Paginacja" class="mt-4">
                <ul class="pagination justify-content-center">
                    {% if budynki.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?q={{ query }}&page={{ budynki.previous_page_number }}"
                               aria-label="Poprzednia"
                               style="color: #9ad1d4;">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for num in budynki.paginator.page_range %}
                        {% if num >= budynki.number|add:'-2' and num <= budynki.number|add:'2' %}
                            {% if budynki.number == num %}
                                <li class="page-item active">
                                    <a class="page-link" href="?q={{ query }}&page={{ num }}"
                                       style="background-color: #9ad1d4; border-color: #9ad1d4;">{{ num }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?q={{ query }}&page={{ num }}"
                                       style="color: #9ad1d4;">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {% if budynki.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?q={{ query }}&page={{ budynki.next_page_number }}"
                               aria-label="Następna"
                               style="color: #9ad1d4;">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            <!-- Koniec Sekcji Paginacja -->
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="bg py-4" style="background-color: #e8f6f3;">
            <div class="container">
                <div class="row align-items-center g-2 g-lg-3">
                    <div class="col-12 col-md-6 text-center text-md-start">
                        <p>&copy; 2024 Artur Gołata</p>
                    </div>
                    <div class="col-12 col-md-6 text-center text-md-end"></div>
                </div>
            </div>
        </div>
    </footer>
{% endblock content %}

panel/templates/form.html
{% extends 'base_sm.html' %}
{% block content %}

<div class="container my-4">
    <h2 class="text-center">Zgłoszenie</h2>
    <div class="card shadow-sm mx-auto" style="max-width: 600px;">
        <div class="card-body">
            <form method="post" action="{% url 'formularz_zgloszeniowy' %}">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_osiedle" class="form-label">{{ form.osiedle.label }}</label>
                    {{ form.osiedle }}
                </div>

                <div class="mb-3">
                    <label for="id_budynek" class="form-label">{{ form.budynek.label }}</label>
                    {{ form.budynek }}
                </div>

                <div class="mb-3">
                    <label for="id_temat" class="form-label">{{ form.temat.label }}</label>
                    {{ form.temat }}
                </div>

                <div class="mb-3">
                    <label for="id_content" class="form-label">{{ form.content.label }}</label>
                    {{ form.content }}
                </div>

                <div class="mb-3">
                    <label for="id_phone" class="form-label">{{ form.phone.label }}</label>
                    {{ form.phone }}
                </div>

                <div class="text-center mt-4">
                    <button type="submit" class="btn btn-primary btn-block">Wyślij zgłoszenie</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_osiedle').change(function () {
            const osiedleId = $(this).val();
            if (osiedleId) {
                $.ajax({
                    url: "{% url 'pobierz_budynki' %}",
                    data: {
                        'osiedle': osiedleId
                    },
                    success: function (data) {
                        const budynekSelect = $('#id_budynek');
                        budynekSelect.empty();
                        budynekSelect.append('<option value="">Wybierz budynek</option>');
                        data.forEach(function (budynek) {
                            budynekSelect.append('<option value="' + budynek.id + '">' + budynek.ulica + '</option>');
                        });
                    }
                });
            } else {
                $('#id_budynek').empty().append('<option value="">Wybierz budynek</option>');
            }
        });
    });
</script>

{% endblock %}

panel/templates/navbar.html
{% load static %}
<div class="header center header-lg dark">
    <div class="container d-flex justify-content-between align-items-center">
        <div class="header-menu-extra">
            <ul class="list-inline mb-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}">
                        <img
                                src="{% static 'assets/images/logo_smb.jpg' %}"
                                alt="Logo SM Budowlani" style="width: 70px; height: 70px">
                    </a>
                </li>
            </ul>
        </div>

        <div class="d-flex align-items-center">
            <form class="d-flex" method="GET" action="{% url 'dashboard' %}">
                <input class="form-control me-2" type="search" placeholder="Szukaj budynku..." name="q"
                       aria-label="Szukaj"
                       style="width: 300px; height: 38px; border-radius: 15px; border-color: #6c757d; background-color: #e8f6f3; color: #5a6268;"
                       value="{{ query }}">
                <button class="btn" type="submit"
                        style="background-color: #9ad1d4; color: #5a6268; border-radius: 15px; height: 38px;">Szukaj
                </button>&nbsp;
                <a href="{% url 'dashboard' %}" class="btn"
                   style="background-color: #9ad1d4; color: #5a6268; border-radius: 15px; height: 38px;">Wyczyść</a>
            </form>

        </div>
        <button class="header-toggle">
            <span></span>
        </button>
    </div>
</div>

panel/templates/navbar_sm.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-center">
    <ul class="navbar-nav ms-center">
        <li class="nav-item">
            <a class="btn btn-outline-success" href="{% url 'dashboard' %}">Powrót &nbsp;
                <i class="fa fa-home" aria-hidden="true"></i>
            </a>
        </li>&nbsp;
        <li class="nav-item">
            <a class="btn btn-outline-success" href="{% url 'formularz_zgloszeniowy' %}">Zgłoś problem &nbsp;
                <i class="bi bi-envelope-fill" aria-hidden="true"></i>
            </a>
        </li>&nbsp;
    </ul>
</nav>